const comunas = [
    {"name":"Cerrillos"},
    {"name":"Cerro Navia"},
    {"name":"Conchali"},
    {"name":"El Bosque"},
    {"name":"Estacion Central"},
    {"name":"Huechuraba"},
    {"name":"Independencia"},
    {"name":"La Cisterna"},
    {"name":"La Florida"},
    {"name":"La Granja"},
    {"name":"La Pintana"},
    {"name":"La Reina"},
    {"name":"Las Condes"},
    {"name":"Lo Barnechea"},
    {"name":"Lo Espejo"},
    {"name":"Lo Prado"},
    {"name":"Macul"},
    {"name":"Maipu"},
    {"name":"Ñuñoa"},
    {"name":"Pedro Aguirre Cerda"},
    {"name":"Peñalolen"},
    {"name":"Providencia"},
    {"name":"Pudahuel"},
    {"name":"Quilicura"},
    {"name":"Quinta Normal"},
    {"name":"Recoleta"},
    {"name":"Renca"},
    {"name":"Santiago"},
    {"name":"San Joaquin"},
    {"name":"San Miguel"},
    {"name":"San Ramon"},
    {"name":"Vitacura"},
    {"name":"Puente Alto"},
    {"name":"Pirque"},
    {"name":"San Jose de Maipo"},
    {"name":"Colina"},
    {"name":"Lampa"},
    {"name":"Tiltil"},
    {"name":"San Bernardo"},
    {"name":"Buin"},
    {"name":"Calera de Tango"},
    {"name":"Paine"},
    {"name":"Melipilla"},
    {"name":"Alhue"},
    {"name":"Curacavi"},
    {"name":"Maria Pinto"},
    {"name":"San Pedro"},
    {"name":"Talagante"},
    {"name":"El Monte"},
    {"name":"Isla de Maipo"},
    {"name":"Padre Hurtado"},
    {"name":"Peñaflor"}
  ];

  // comunas.sort((a,b) => (a.name < b.name) ? -1 : (a.name > b.name) ? 1 :0)

  module.exports = comunas;